# Gradle
org.gradle.jvmargs = -Xmx4G -Xms4G
org.gradle.daemon = false

# Mod Properties
mod_id = fbp
mod_name = Fancy Block Particles Reforged

# Combined with the git tag (mc_version) by gradleutils to form the full version, e.g. 26.2-1.0.0
mod_version_label = 1.0.1

# Minecraft
mc_version = 26.3

neo_version = 26.3.0.1-beta

loader_version = 0.19.5
fabric_version = 0.160.5

java_version = 25

# Dependencies
modmenu_version = 21.0.0-beta.1

sereneseasons_version = 26.1.2.0.4
glitchcore_version = 26.2.0.0.0

sodium_version = 0.9.2
iris_version = 1.11.5

oculus_version = 1.20.1-1.7.0

spark_version = 1.10.185

mixin_extras_version = 0.5.4

lombok_version = 1.18.+