license="GPLv3"
issueTrackerURL="https://github.com/Romoslayer/Fancy-Block-Particles-Reforged/issues"

[[mods]]
    modId="fbp"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/fancy-block-particles-reforged"
    displayTest="IGNORE_ALL_VERSION"
    logoFile="logo.png"
    updateJSONURL="https://raw.githubusercontent.com/Romoslayer/Fancy-Block-Particles-Reforged/${mc_version}/update.json"
    authors="Hantonik, TominoCZ, Romoslayer"
    credits="Original mod by MorphoxL, continued as FBP Renewed by Hantonik and TominoCZ"
    description='''3D Digging particles! YAY!'''

[[mixins]]
    config="${mod_id}.mixins.json"
[[mixins]]
    config="${mod_id}.neoforge.mixins.json"

[[dependencies.fbp]]
    modId="neoforge"
    type="required"
    versionRange="[26.2.0.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.fbp]]
    modId="minecraft"
    type="required"
    versionRange="[26.2,26.3)"
    ordering="NONE"
    side="CLIENT"
